version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017

  auth:
    build: ./auth-service
#      context: .
#    container_name: auth-service
    ports:
      - "5050:5050"
    environment:
      PORT_ONE: 5050
      MONGO_URI: mongodb://mongo:27017/auth-service
    depends_on:
      - mongo

  order:
    build: ./order-service
#      context: .
#    container_name: order-service
    ports:
      - "9090:9090"
    environment:
      PORT_ONE: 9090
      MONGO_URI: mongodb://mongo:27017/order-service
    depends_on:
      - mongo

  product:
    build: ./product-service
#      context: .
#    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      PORT_ONE: 8080
      MONGO_URI: mongodb://mongo:27017/product-service
    depends_on:
      - mongo

  review:
    build: ./review
#      context: .
#    container_name: product-service
    ports:
      - "8000:8000"
    environment:
      PORT_ONE: 8000
      MONGO_URI: mongodb://mongo:27017/review
    depends_on:
      - mongo